#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
set -e

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib64
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}



PATH=$PATH:${APPDIR}/rstudio/bin
export PATH

cd ${HOME}

exec ${APPDIR}/rstudio/bin/rstudio $@
